### ISSUE TITLE
Installation bug - Needs updated documentation

### ISSUE THREAD

**Issue by hayator** [Originate/text-runner#305]
When user runs "node_modules/.bin/text-run help"

![image](https://user-images.githubusercontent.com/11418824/36285991-af4eadfa-127b-11e8-944e-38e3429c5d66.png)

**Comment by kevgo** [comment]
Yes that's a known issue. I am experimenting with a new way of deploying it.

**Comment by kevgo** [comment]
This is fixed in version 1.0.4
